# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './settings_dlg_2.ui'
#
# Created: Mon May 18 00:49:12 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(573, 576)
        Dialog.setMaximumSize(QtCore.QSize(600, 16777215))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.targetDevHelpButton = QtGui.QPushButton(Dialog)
        self.targetDevHelpButton.setObjectName("targetDevHelpButton")
        self.gridLayout.addWidget(self.targetDevHelpButton, 1, 5, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.rockboxPathHelpButton = QtGui.QPushButton(Dialog)
        self.rockboxPathHelpButton.setObjectName("rockboxPathHelpButton")
        self.gridLayout.addWidget(self.rockboxPathHelpButton, 2, 5, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 2)
        self.navFolderChangeButton = QtGui.QPushButton(Dialog)
        self.navFolderChangeButton.setObjectName("navFolderChangeButton")
        self.gridLayout.addWidget(self.navFolderChangeButton, 3, 4, 1, 1)
        self.navFolderHelpButton = QtGui.QPushButton(Dialog)
        self.navFolderHelpButton.setObjectName("navFolderHelpButton")
        self.gridLayout.addWidget(self.navFolderHelpButton, 3, 5, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 2)
        self.plFolderChangeButton = QtGui.QPushButton(Dialog)
        self.plFolderChangeButton.setObjectName("plFolderChangeButton")
        self.gridLayout.addWidget(self.plFolderChangeButton, 4, 4, 1, 1)
        self.plFolderHelpButton = QtGui.QPushButton(Dialog)
        self.plFolderHelpButton.setObjectName("plFolderHelpButton")
        self.gridLayout.addWidget(self.plFolderHelpButton, 4, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 5, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 15, 5, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.musicspaceFileChangeButton = QtGui.QPushButton(Dialog)
        self.musicspaceFileChangeButton.setObjectName("musicspaceFileChangeButton")
        self.gridLayout.addWidget(self.musicspaceFileChangeButton, 5, 4, 1, 1)
        self.musicspaceFileHelpButton = QtGui.QPushButton(Dialog)
        self.musicspaceFileHelpButton.setObjectName("musicspaceFileHelpButton")
        self.gridLayout.addWidget(self.musicspaceFileHelpButton, 5, 5, 1, 1)
        self.rockboxPathChangeButton = QtGui.QPushButton(Dialog)
        self.rockboxPathChangeButton.setObjectName("rockboxPathChangeButton")
        self.gridLayout.addWidget(self.rockboxPathChangeButton, 2, 4, 1, 1)
        self.targetComboBox = QtGui.QComboBox(Dialog)
        self.targetComboBox.setObjectName("targetComboBox")
        self.gridLayout.addWidget(self.targetComboBox, 1, 4, 1, 1)
        self.musicspaceDropoffHelpButton = QtGui.QPushButton(Dialog)
        self.musicspaceDropoffHelpButton.setObjectName("musicspaceDropoffHelpButton")
        self.gridLayout.addWidget(self.musicspaceDropoffHelpButton, 11, 5, 1, 1)
        self.musicspaceDropoffSpinBox = QtGui.QDoubleSpinBox(Dialog)
        self.musicspaceDropoffSpinBox.setDecimals(1)
        self.musicspaceDropoffSpinBox.setSingleStep(0.1)
        self.musicspaceDropoffSpinBox.setObjectName("musicspaceDropoffSpinBox")
        self.gridLayout.addWidget(self.musicspaceDropoffSpinBox, 11, 4, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 13, 0, 1, 1)
        self.lastfmUsersLineEdit = QtGui.QLineEdit(Dialog)
        self.lastfmUsersLineEdit.setObjectName("lastfmUsersLineEdit")
        self.gridLayout.addWidget(self.lastfmUsersLineEdit, 10, 4, 1, 1)
        self.lastfmQueriesComboBox = QtGui.QComboBox(Dialog)
        self.lastfmQueriesComboBox.setObjectName("lastfmQueriesComboBox")
        self.gridLayout.addWidget(self.lastfmQueriesComboBox, 13, 4, 1, 1)
        self.lastfmQueriesHelpButton = QtGui.QPushButton(Dialog)
        self.lastfmQueriesHelpButton.setObjectName("lastfmQueriesHelpButton")
        self.gridLayout.addWidget(self.lastfmQueriesHelpButton, 13, 5, 1, 1)
        self.lastfmUsersHelpButton = QtGui.QPushButton(Dialog)
        self.lastfmUsersHelpButton.setObjectName("lastfmUsersHelpButton")
        self.gridLayout.addWidget(self.lastfmUsersHelpButton, 10, 5, 1, 1)
        self.label.setBuddy(self.targetComboBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Target device", None, QtGui.QApplication.UnicodeUTF8))
        self.targetDevHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Location of rockbox device", None, QtGui.QApplication.UnicodeUTF8))
        self.rockboxPathHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Output folder for navigation links", None, QtGui.QApplication.UnicodeUTF8))
        self.navFolderChangeButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.navFolderHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Output folder for playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.plFolderChangeButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.plFolderHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Musicspace file", None, QtGui.QApplication.UnicodeUTF8))
        self.musicspaceFileChangeButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.musicspaceFileHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.rockboxPathChangeButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.musicspaceDropoffHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Musicspace probability drop-off parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Last.fm users", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Last.fm queries before giving up", None, QtGui.QApplication.UnicodeUTF8))
        self.lastfmQueriesHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.lastfmUsersHelpButton.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))

